spring:
  datasource:
    url: jdbc:h2:tcp://${H2_HOST}/~/${DB_NAME}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  issuer: ${JWT_ISSUER}